AI Assignment 2

Name : Gangisetty Krishna Vamsi

Reg.No : 20BDS0281

college : VIT Vellore

email :gangikrishna.vamsi2020@vitstudent.ac.in

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('drug200.csv')

# Task 1 : Read the dataset and do data pre-processing

In [ ]:
label_encoder = LabelEncoder()
df['Sex'] = label_encoder.fit_transform(df['Sex'])
df['BP'] = label_encoder.fit_transform(df['BP'])
df['Cholesterol'] = label_encoder.fit_transform(df['Cholesterol'])
df['Drug'] = label_encoder.fit_transform(df['Drug'])
print(df.head())

   Age  Sex  BP  Cholesterol  Na_to_K  Drug
0   23    0   0            0   25.355     0
1   47    1   1            0   13.093     3
2   47    1   1            0   10.114     3
3   28    0   2            0    7.798     4
4   61    0   1            0   18.043     0


In [ ]:
# Scale numerical variables
scaler = StandardScaler()
df[['Age', 'Na_to_K']] = scaler.fit_transform(df[['Age', 'Na_to_K']])

In [ ]:
# Separate features and labels
X = df[['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']]
y = df['Drug']

In [ ]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [ ]:
print(X_train.shape)
print(y_test.shape)

(160, 5)
(40,)


# Task 2 : Build the ANN model with (input layer, min 3 hidden layers & output layer)


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
# Define the model architecture
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(5,)))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(5, activation='softmax'))

In [ ]:
x = df.iloc[:,0:5]
y = df.iloc[:,5:]
print(x)
print(y)

          Age  Sex  BP  Cholesterol   Na_to_K
0   -1.291591    0   0            0  1.286522
1    0.162699    1   1            0 -0.415145
2    0.162699    1   1            0 -0.828558
3   -0.988614    0   2            0 -1.149963
4    1.011034    0   1            0  0.271794
..        ...  ...  ..          ...       ...
195  0.708057    0   1            0 -0.626917
196 -1.715759    1   1            0 -0.565995
197  0.465676    1   2            0 -0.859089
198 -1.291591    1   2            1 -0.286500
199 -0.261469    0   1            1 -0.657170

[200 rows x 5 columns]
     Drug
0       0
1       3
2       3
3       4
4       0
..    ...
195     3
196     3
197     4
198     4
199     4

[200 rows x 1 columns]


In [ ]:
# Compile the model
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam',metrics=['accuracy'])
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)
model.fit(X_train, y_train_encoded, epochs=20, batch_size=20,validation_data=(X_test, y_test_encoded))

Epoch 1/20
8/8 [==============================] - 1s 30ms/step - loss: 1.5333 - accuracy: 0.4375 - val_loss: 1.4609 - val_accuracy: 0.5750
Epoch 2/20
8/8 [==============================] - 0s 7ms/step - loss: 1.3591 - accuracy: 0.6687 - val_loss: 1.3021 - val_accuracy: 0.6000
Epoch 3/20
8/8 [==============================] - 0s 4ms/step - loss: 1.1273 - accuracy: 0.6750 - val_loss: 1.0769 - val_accuracy: 0.6000
Epoch 4/20
8/8 [==============================] - 0s 4ms/step - loss: 0.8779 - accuracy: 0.6875 - val_loss: 0.8743 - val_accuracy: 0.6250
Epoch 5/20
8/8 [==============================] - 0s 4ms/step - loss: 0.6731 - accuracy: 0.7625 - val_loss: 0.7003 - val_accuracy: 0.8000
Epoch 6/20
8/8 [==============================] - 0s 4ms/step - loss: 0.5185 - accuracy: 0.8875 - val_loss: 0.5997 - val_accuracy: 0.8250
Epoch 7/20
8/8 [==============================] - 0s 4ms/step - loss: 0.4107 - accuracy: 0.9000 - val_loss: 0.5079 - val_accuracy: 0.8500
Epoch 8/20
8/8 [=================

In [ ]:
y_pred = model.predict(X_test)
y_pred

2/2 [==============================] - 0s 3ms/step


array([[5.7366898e-04, 1.2736394e-04, 1.8535064e-05, 4.1879721e-02,
        9.5740068e-01],
       [9.8324859e-01, 1.0361422e-02, 2.6318815e-04, 5.7714866e-03,
        3.5526982e-04],
       [3.7239156e-06, 1.0364023e-06, 3.1783184e-08, 7.3310221e-03,
        9.9266416e-01],
       [1.6505459e-04, 9.3996857e-04, 1.3556110e-02, 7.2868824e-01,
        2.5665051e-01],
       [9.9999994e-01, 1.6863833e-16, 1.8314687e-14, 5.8122699e-12,
        4.3653178e-13],
       [9.9891889e-01, 4.5725810e-05, 3.0506196e-04, 6.6779141e-04,
        6.2469619e-05],
       [9.9999779e-01, 1.7923405e-08, 7.2562585e-08, 1.7651082e-06,
        2.1409824e-07],
       [3.5240431e-03, 1.5230335e-06, 7.1923319e-07, 2.0866327e-02,
        9.7560734e-01],
       [6.1974034e-02, 6.7531657e-01, 8.1826426e-02, 1.4918542e-01,
        3.1697568e-02],
       [9.9381744e-08, 6.5656098e-09, 2.9737328e-07, 2.8406263e-03,
        9.9715894e-01],
       [5.0144276e-04, 9.9138027e-01, 4.9245381e-04, 7.4816998e-03,
        1.44

In [ ]:
comp = pd.DataFrame(y_test_encoded) # Creating a dataframe
comp.columns = ['Actual Value'] # Changing the column name
comp

Actual Value
0              4
1              0
2              4
3              3
4              0
5              0
6              0
7              4
8              1
9              4
10             1
11             4
12             0
13             1
14             2
15             0
16             2
17             4
18             3
19             0
20             2
21             4
22             4
23             0
24             0
25             0
26             3
27             4
28             0
29             4
30             0
31             3
32             3
33             0
34             1
35             0
36             4
37             1
38             0
39             1

In [ ]:
# Print the model summary
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                384       
                                                                 
 dense_1 (Dense)             (None, 128)               8320      
                                                                 
 dense_2 (Dense)             (None, 64)                8256      
                                                                 
 dense_3 (Dense)             (None, 32)                2080      
                                                                 
 dense_4 (Dense)             (None, 5)                 165       
                                                                 
Total params: 19,205
Trainable params: 19,205
Non-trainable params: 0
_________________________________________________________________


# Task 3 : Test the model with random data

In [ ]:
# Generate random data for testing
random_data = np.random.rand(1, 5)
random_data

array([[0.58857633, 0.45966327, 0.11338478, 0.10455691, 0.29322196]])

In [ ]:
# Make predictions
predictions = model.predict(random_data)
predictions

1/1 [==============================] - 0s 49ms/step


array([[9.9934596e-01, 1.7040064e-05, 1.7047777e-04, 3.6303891e-04,
        1.0353992e-04]], dtype=float32)

In [ ]:
# Get the predicted drug class
predicted_class = np.argmax(predictions)

In [ ]:
# Print the predicted class
print("Predicted Drug Class :", predicted_class)

Predicted Drug Class : 0
